### ISSUE TITLE
Removal of outdated packages with out paccache

### ISSUE THREAD

**Issue by chrishoage** [nroi/flexo#39]
Thank you for this wonderful tool! 

I'm using https://github.com/docker-flexo/docker-flexo which is based on debian, and I'm hosting it on an ubuntu sever. 

Furthermore I'm using a named docker-compose volume to store the cache like so 

```yml
  flexo:
    restart: ${RESTART-unless-stopped}
    image: nroi/flexo
    container_name: flexo
    volumes:
      - flexo-cache:/var/cache/flexo
```

All this put together makes it a challenge to run `paccache -r`. Currently the best solution is to spin up a temporary docker container using the archlinux image, mount the named volume, and run the command in the README using `paccache -r`. 

While this works it would be nice if flexo would prune old packages on its own with out the use of `paccache -r`. 

Is this in scope?
